using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VISIDA_API.Models.FCT
{
    public interface INutrientData
    {
        int Id { get; set; }

        double? EnergykCal { get; set; }
        double? EnergyWFibre { get; set; }
        double? EnergyWoFibre { get; set; }
        double? EnergykJ { get; set; }
        double? Moisture { get; set; }
        double? Protein { get; set; }
        double? Fat { get; set; }
        double? SaturatedFat { get; set; }
        double? MonounsaturatedFat { get; set; }
        double? PolyunsaturatedFat { get; set; }
        double? LinoleicAcic { get; set; }
        double? AlphaLinolenicAcid { get; set; }
        double? CarbohydratesWoSa { get; set; }
        double? Carbohydrates { get; set; }
        double? Starch { get; set; }
        double? SugarTotal { get; set; }
        double? SugarAdded { get; set; }
        double? SugarFree { get; set; }
        double? Fibre { get; set; }
        double? Alcohol { get; set; }
        double? Ash { get; set; }
        double? Retinol { get; set; }
        double? BetaCarotene { get; set; }
        double? ProvitaminA { get; set; }
        double? VitaminA { get; set; }
        double? Thiamin { get; set; }
        double? Riboflavin { get; set; }
        double? Niacin { get; set; }
        double? NiacinDE { get; set; }
        double? VitaminB6 { get; set; }
        double? VitaminB12 { get; set; }
        double? VitaminC { get; set; }
        double? AlphaTocopherol { get; set; }
        double? VitaminE { get; set; }
        double? Folate { get; set; }
        double? FolicAcid { get; set; }
        double? FolatesTotal { get; set; }
        double? FolateDietary { get; set; }
        double? Calcium { get; set; }
        double? Iodine { get; set; }
        double? Phosphorus { get; set; }
        double? Sodium { get; set; }
        double? Potassium { get; set; }
        double? Iron { get; set; }
        double? Magnesium { get; set; }
        double? Selenium { get; set; }
        double? Copper { get; set; }
        double? Zinc { get; set; }
        double? Caffeine { get; set; }
        double? Tryptophan { get; set; }
        double? Eicosapentaenoic { get; set; }
        double? Docosapentaenoic { get; set; }
        double? Docosahexaenoic { get; set; }
        double? Omega3FattyAcid { get; set; }
        double? TransFattyAcid { get; set; }
        double? Cholesterol { get; set; }
        double? ADG_10 { get; set; }
        double? ADG_101 { get; set; }
        double? ADG_1011 { get; set; }
        double? ADG_1012 { get; set; }
        double? ADG_1013 { get; set; }
        double? ADG_1014 { get; set; }
        double? ADG_1015 { get; set; }
        double? ADG_1016 { get; set; }
        double? ADG_1017 { get; set; }
        double? ADG_1018 { get; set; }
        double? ADG_102 { get; set; }
        double? ADG_1021 { get; set; }
        double? ADG_1022 { get; set; }
        double? ADG_1023 { get; set; }
        double? ADG_1024 { get; set; }
        double? ADG_1025 { get; set; }
        double? ADG_1026 { get; set; }
        double? ADG_1027 { get; set; }
        double? ADG_1028 { get; set; }
        double? ADG_20 { get; set; }
        double? ADG_201 { get; set; }
        double? ADG_202 { get; set; }
        double? ADG_203 { get; set; }
        double? ADG_204 { get; set; }
        double? ADG_205 { get; set; }
        double? ADG_2051 { get; set; }
        double? ADG_2052 { get; set; }
        double? ADG_30 { get; set; }
        double? ADG_301 { get; set; }
        double? ADG_302 { get; set; }
        double? ADG_303 { get; set; }
        double? ADG_40 { get; set; }
        double? ADG_401 { get; set; }
        double? ADG_4011 { get; set; }
        double? ADG_4012 { get; set; }
        double? ADG_402 { get; set; }
        double? ADG_4021 { get; set; }
        double? ADG_4022 { get; set; }
        double? ADG_4023 { get; set; }
        double? ADG_4024 { get; set; }
        double? ADG_4025 { get; set; }
        double? ADG_4026 { get; set; }
        double? ADG_4027 { get; set; }
        double? ADG_4028 { get; set; }
        double? ADG_403 { get; set; }
        double? ADG_4031 { get; set; }
        double? ADG_4032 { get; set; }
        double? ADG_4033 { get; set; }
        double? ADG_4034 { get; set; }
        double? ADG_4035 { get; set; }
        double? ADG_4036 { get; set; }
        double? ADG_4037 { get; set; }
        double? ADG_4038 { get; set; }
        double? ADG_4039 { get; set; }
        double? ADG_50 { get; set; }
        double? ADG_501 { get; set; }
        double? ADG_5011 { get; set; }
        double? ADG_5012 { get; set; }
        double? ADG_502 { get; set; }
        double? ADG_5021 { get; set; }
        double? ADG_5022 { get; set; }
        double? ADG_503 { get; set; }
        double? ADG_5031 { get; set; }
        double? ADG_5032 { get; set; }
        double? ADG_504 { get; set; }
        double? ADG_5041 { get; set; }
        double? ADG_5042 { get; set; }
        double? ADG_505 { get; set; }
        double? ADG_506 { get; set; }
        double? ADG_507 { get; set; }
        double? ADG_5071 { get; set; }
        double? ADG_5072 { get; set; }
        double? ADG_508 { get; set; }
        double? ADG_60 { get; set; }
        double? ADG_70 { get; set; }
        double? ADG_701 { get; set; }
        double? ADG_702 { get; set; }
        double? ADG_703 { get; set; }

    }
}