// <auto-generated />
namespace VISIDA_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Track24HR : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Track24HR));
        
        string IMigrationMetadata.Id
        {
            get { return "202006110100585_Track24HR"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
